--- drivers/gpu/drm/amd/amdgpu/Makefile
+++ drivers/gpu/drm/amd/amdgpu/Makefile
@@ -190,6 +190,7 @@ amdgpu-$(CONFIG_COMPAT) += amdgpu_ioc32.o
 amdgpu-$(CONFIG_VGA_SWITCHEROO) += amdgpu_atpx_handler.o
 amdgpu-$(CONFIG_ACPI) += amdgpu_acpi.o
 amdgpu-$(CONFIG_HMM_MIRROR) += amdgpu_mn.o
+amdgpu-$(CONFIG_X86_PS4) += ps4_bridge.o
 
 include $(FULL_AMD_PATH)/powerplay/Makefile
 
